version: "3.9"
services:
  backend:
    build: .
    ports:
      - 5000:5000
    networks:
            app_net:
                ipv4_address: 172.16.238.2
  frontend:
    build: ./client
    ports:
      - 3000:3000
    networks:
            app_net:
                ipv4_address: 172.16.238.3

networks:
    app_net:
        ipam:
            driver: default
            config:
            - subnet: "172.16.238.0/24"
